// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Stylesheets;
using Content.Shared._Mini.MiniCCVars;
using Content.Shared.CCVar;
using Content.Shared.Dataset;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Timing;

namespace Content.Client.Launcher
{
    [GenerateTypedNameReferences]
    public sealed partial class LauncherConnectingGui : Control
    {
        private const float RedialWaitTimeSeconds = 15f;
        private const string WhitelistGateKey = "whitelist";
        private const string DiscordInviteFallback = "https://discord.gg/mini-station-oasis";

        private readonly LauncherConnecting _state;
        private float _waitTime;

        // Pressing reconnect will redial instead of simply reconnecting.
        private bool _redial;
        private bool _whitelistDenied;
        private string? _discordInvite;
        private string? _lastFailReason;

        private readonly IRobustRandom _random;
        private readonly IPrototypeManager _prototype;
        private readonly IConfigurationManager _cfg;
        private readonly IClipboardManager _clipboard;
        private readonly IStylesheetManager _stylesheetManager;
        private readonly IUriOpener _uriOpener;

        public LauncherConnectingGui(LauncherConnecting state, IRobustRandom random,
            IPrototypeManager prototype, IConfigurationManager config, IClipboardManager clipboard)
        {
            _state = state;
            _random = random;
            _prototype = prototype;
            _cfg = config;
            _clipboard = clipboard;
            _stylesheetManager = IoCManager.Resolve<IStylesheetManager>();
            _uriOpener = IoCManager.Resolve<IUriOpener>();

            RobustXamlLoader.Load(this);

            LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

            // Mini: StyleNano carries UiFontStyle / accents. SheetSystem always uses stock Noto.
            ApplyMiniStylesheet();
            RefreshCoinLabel();

            ChangeLoginTip();
            RetryButton.OnPressed += ReconnectButtonPressed;
            ReconnectButton.OnPressed += ReconnectButtonPressed;
            WhitelistRetryButton.OnPressed += ReconnectButtonPressed;

            CopyButton.OnPressed += CopyButtonPressed;
            CopyButtonDisconnected.OnPressed += CopyButtonDisconnectedPressed;
            WhitelistCopyButton.OnPressed += WhitelistCopyButtonPressed;
            WhitelistDiscordButton.OnPressed += WhitelistDiscordButtonPressed;
            ExitButton.OnPressed += _ => _state.Exit();

            WhitelistBody.SetMessage(Loc.GetString("connecting-whitelist-body"));

            var addr = state.Address;
            if (addr != null)
                ConnectingAddress.Text = addr;

            state.PageChanged += OnPageChanged;
            state.ConnectFailReasonChanged += ConnectFailReasonChanged;
            state.ConnectionStateChanged += ConnectionStateChanged;
            state.ConnectFailed += HandleDisconnectReason;

            ConnectionStateChanged(state.ConnectionState);

            // Live /status poll removed — it required a matching engine build and crashed mismatched launchers.
            StatusPlayers.Text = Loc.GetString("connecting-info-players-unavailable");
            StatusMap.Text = Loc.GetString("connecting-info-map-unavailable");
            StatusPreset.Text = Loc.GetString("connecting-info-preset-unavailable");

            // Redial flag setup
            var edim = IoCManager.Resolve<ExtendedDisconnectInformationManager>();
            edim.LastNetDisconnectedArgsChanged += LastNetDisconnectedArgsChanged;
            LastNetDisconnectedArgsChanged(edim.LastNetDisconnectedArgs);
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            _stylesheetManager.StylesheetsUpdated += OnStylesheetsUpdated;
            ApplyMiniStylesheet();
            RefreshCoinLabel();
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();
            _stylesheetManager.StylesheetsUpdated -= OnStylesheetsUpdated;
        }

        private void OnStylesheetsUpdated()
        {
            ApplyMiniStylesheet();
        }

        private void ApplyMiniStylesheet()
        {
            Stylesheet = _stylesheetManager.SheetNano;
        }

        private void RefreshCoinLabel()
        {
            if (!_cfg.GetCVar(MiniCCVars.CachedCoinBalanceKnown))
            {
                StatusCoins.Text = Loc.GetString("connecting-info-coins-unknown");
                return;
            }

            var balance = _cfg.GetCVar(MiniCCVars.CachedCoinBalance);
            StatusCoins.Text = Loc.GetString("connecting-info-coins", ("balance", balance));
        }

        // Just button, there's only one at once anyways :)
        private void ReconnectButtonPressed(BaseButton.ButtonEventArgs args)
        {
            if (_redial)
            {
                // Redial shouldn't fail, but if it does, try a reconnect (maybe we're being run from debug)
                if (_state.Redial())
                    return;
            }

            _state.RetryConnect();
        }

        private void CopyButtonPressed(BaseButton.ButtonEventArgs args)
        {
            CopyText(ConnectFailReason.Text);
        }

        private void CopyButtonDisconnectedPressed(BaseButton.ButtonEventArgs args)
        {
            CopyText(DisconnectReason.Text);
        }

        private void WhitelistCopyButtonPressed(BaseButton.ButtonEventArgs args)
        {
            CopyText(_lastFailReason ?? WhitelistBody.Text);
        }

        private void WhitelistDiscordButtonPressed(BaseButton.ButtonEventArgs args)
        {
            var invite = _discordInvite;
            if (string.IsNullOrWhiteSpace(invite))
                invite = DiscordInviteFallback;

            // Client sandbox forbids System.UriKind / Uri.TryCreate — use string OpenUri.
            if (!invite.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
                && !invite.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
                return;

            try
            {
                _uriOpener.OpenUri(invite);
            }
            catch (Exception)
            {
                // Ignore invalid invite URLs from the server.
            }
        }

        private void CopyText(string? text)
        {
            if (!string.IsNullOrEmpty(text))
            {
                _clipboard.SetText(text);
            }
        }

        private void ConnectFailReasonChanged(string? reason)
        {
            _lastFailReason = reason;
            ConnectFailReason.SetMessage(reason == null
                ? ""
                : Loc.GetString("connecting-fail-reason", ("reason", reason)));
        }

        private void LastNetDisconnectedArgsChanged(NetDisconnectedArgs? args)
        {
            HandleDisconnectReason(args);
        }

        private void HandleDisconnectReason(INetStructuredReason? reason)
        {
            if (reason == null)
            {
                _waitTime = 0;
                _redial = false;
                _whitelistDenied = false;
                _discordInvite = null;
            }
            else
            {
                _redial = reason.RedialFlag;

                if (reason.Message.Int32Of("delay") is { } delay)
                {
                    _waitTime = delay;
                }
                else if (_redial)
                {
                    _waitTime = RedialWaitTimeSeconds;
                }

                var gate = reason.Message.StringOf("gate");
                _whitelistDenied = gate == WhitelistGateKey
                    || IsWhitelistReasonFallback(reason.Reason);
                _discordInvite = reason.Message.StringOf("discord");

                if (_whitelistDenied && _state.CurrentPage == LauncherConnecting.Page.ConnectFailed)
                    ApplyFailPageVisibility();
            }
        }

        private static bool IsWhitelistReasonFallback(string? reason)
        {
            if (string.IsNullOrEmpty(reason))
                return false;

            return reason.Contains("whitelist", StringComparison.OrdinalIgnoreCase)
                   || reason.Contains("белый список", StringComparison.OrdinalIgnoreCase)
                   || reason.Contains("Закрытый набор", StringComparison.OrdinalIgnoreCase)
                   || reason.Contains("Closed enrollment", StringComparison.OrdinalIgnoreCase);
        }

        private void ChangeLoginTip()
        {
            var tipsDataset = _cfg.GetCVar(CCVars.LoginTipsDataset);
            var loginTipsEnabled = _prototype.TryIndex<LocalizedDatasetPrototype>(tipsDataset, out var tips);

            LoginTips.Visible = loginTipsEnabled;
            if (!loginTipsEnabled)
            {
                return;
            }

            var tipList = tips!.Values;

            if (tipList.Count == 0)
                return;

            var randomIndex = _random.Next(tipList.Count);
            var tip = tipList[randomIndex];
            LoginTip.SetMessage(Loc.GetString(tip));

            LoginTipTitle.Text = Loc.GetString("connecting-window-tip", ("numberTip", randomIndex));
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            var button = _state.CurrentPage == LauncherConnecting.Page.ConnectFailed
                ? (_whitelistDenied ? WhitelistRetryButton : RetryButton)
                : ReconnectButton;

            _waitTime -= args.DeltaSeconds;
            if (_waitTime <= 0)
            {
                button.Disabled = false;
                var key = _redial
                    ? "connecting-redial"
                    : _state.CurrentPage == LauncherConnecting.Page.ConnectFailed
                        ? "connecting-reconnect"
                        : "connecting-retry";

                button.Text = Loc.GetString(key);
            }
            else
            {
                button.Disabled = true;
                button.Text = Loc.GetString("connecting-redial-wait", ("time", _waitTime.ToString("00.000")));
            }
        }

        private void OnPageChanged(LauncherConnecting.Page page)
        {
            ConnectingStatus.Visible = page == LauncherConnecting.Page.Connecting;
            Disconnected.Visible = page == LauncherConnecting.Page.Disconnected;

            if (page == LauncherConnecting.Page.ConnectFailed)
            {
                ApplyFailPageVisibility();
            }
            else
            {
                ConnectFail.Visible = false;
                WhitelistDenied.Visible = false;
            }

            if (page == LauncherConnecting.Page.Disconnected)
                DisconnectReason.Text = _state.LastDisconnectReason;

            if (page == LauncherConnecting.Page.Connecting)
            {
                _whitelistDenied = false;
                _discordInvite = null;
            }
        }

        private void ApplyFailPageVisibility()
        {
            WhitelistDenied.Visible = _whitelistDenied;
            ConnectFail.Visible = !_whitelistDenied;
            WhitelistDiscordButton.Disabled = false;
            WhitelistDiscordButton.ToolTip = _discordInvite ?? DiscordInviteFallback;
        }

        private void ConnectionStateChanged(ClientConnectionState state)
        {
            ConnectStatus.Text = Loc.GetString($"connecting-state-{state}");
        }
    }
}
