using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Shared.Prototypes;
using Content.Shared._Arcane.ErpPanel;
using System.Linq;
using Robust.Client.UserInterface.Controls;
using Robust.Client.Graphics;
using Content.Client.Stylesheets;
using Robust.Client.GameObjects;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Content.Shared.IdentityManagement;
using Content.Shared._Arcane.ERP;

namespace Content.Client._Arcane.ErpPanel;

[GenerateTypedNameReferences]
public sealed partial class ErpPanelWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    private readonly SpriteSystem _sprite;
    private readonly ArousalSystem _arousal;

    private static readonly Color BackgroundColor = new Color(26, 18, 36);
    private static readonly Color FrameColor = new Color(88, 40, 140);
    private static readonly Color ButtonColor = new Color(90, 55, 130);
    private static readonly Color ButtonFrameColor = new Color(192, 132, 252);

    private HashSet<string> _openedCategories = new();
    private TimeSpan _lastInteractionUpdate = TimeSpan.Zero;
    private static readonly TimeSpan ReloadCooldown = TimeSpan.FromMilliseconds(80);
    private TimeSpan _lastArousalUpdate = TimeSpan.Zero;
    private static readonly TimeSpan ArousalUpdateCooldown = TimeSpan.FromMilliseconds(50);

    private EntityUid? _currentUser;
    private EntityUid? _currentTarget;
    private List<string> _currentInteractions = new();
    private Dictionary<Button, (TimeSpan, TimeSpan)> _cooldowns = new(); // Кнопка, время последнего использования, кулдаун

    public Action<string, float, float>? OnSendEmote;

    public ErpPanelWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entManager.System<SpriteSystem>();
        _arousal = _entManager.System<ArousalSystem>();

        SearchInput.OnTextChanged += _ => ReloadInteractionsIfNeeded(true);

        CustomArousalButton.OnPressed += _ => SetArousalSliderVisible(!ArousalSlider.Visible);
        CustomMoaningButton.OnPressed += _ => SetMoaningSliderVisible(!MoaningSlider.Visible);

        ArousalSlider.OnValueChanged += _ =>
        {
            var value = (int) ArousalSlider.Value;
            ArousalLabel.Text = $"{value}%";
        };

        MoaningSlider.OnValueChanged += _ =>
        {
            var value = (int) MoaningSlider.Value;
            MoaningLabel.Text = $"{value}%";
        };
    }

    public void SetTarget(NetEntity user, NetEntity target)
    {
        _currentUser = _entManager.GetEntity(user);
        _currentTarget = _entManager.GetEntity(target);

        _currentInteractions.Clear();

        if (_currentUser == null || _currentTarget == null)
            return;

        var targetName = Identity.Name(_currentTarget.Value,
                                       _entManager,
                                       _currentUser.Value);

        HeaderLabel.Text = Loc.GetString("erp-panel-header", ("target", targetName));

        ReloadInteractionsIfNeeded(true);
    }

    private void SetArousalSliderVisible(bool visible)
    {
        CustomArousalButton.Pressed = visible;
        ArousalSlider.Visible = visible;
    }

    private void SetMoaningSliderVisible(bool visible)
    {
        CustomMoaningButton.Pressed = visible;
        MoaningSlider.Visible = visible;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!IsOpen)
            return;

        UpdateCooldowns();
        UpdateArousal();
        ReloadInteractionsIfNeeded();
    }

    private void UpdateCooldowns()
    {
        var now = _timing.CurTime;
        var buttons = _cooldowns.Keys.ToList();
        foreach (var button in buttons)
        {
            var (lastUse, cooldown) = _cooldowns[button];
            if (now - lastUse >= cooldown)
            {
                _cooldowns.Remove(button);
                button.Disabled = false;
                continue;
            }

            button.Disabled = true;
        }
    }

    private void UpdateArousal()
    {
        if (_lastArousalUpdate + ArousalUpdateCooldown > _timing.CurTime)
            return;
        _lastArousalUpdate = _timing.CurTime;

        if (!_entManager.TryGetComponent<ArousalComponent>(_currentUser, out var userArousal))
            return;

        var percent = _arousal.GetArousal(userArousal) / userArousal.MaxArousal;
        var targetValue = Math.Clamp(percent, 0f, 1f);
        var diff = targetValue - ArousalProgressBar.Value;

        ArousalProgressBar.Value += 0.1f * diff;
    }

    private void ReloadInteractionsIfNeeded(bool force = false)
    {
        if (!_currentUser.HasValue || !_currentTarget.HasValue)
            return;

        var now = _timing.CurTime;
        if (!force && now < _lastInteractionUpdate + ReloadCooldown)
            return;

        _lastInteractionUpdate = now;

        if (!TryUpdateCurrentInteractions())
            return;

        ReloadInteractions(_currentUser.Value, _currentTarget.Value);
    }

    private bool TryUpdateCurrentInteractions()
    {
        if (!_currentUser.HasValue || !_currentTarget.HasValue)
            return false;

        var user = _currentUser.Value;
        var target = _currentTarget.Value;

        var interactions = _prototypeManager.EnumeratePrototypes<PanelInteractionPrototype>();

        var newInteractions = new List<string>();
        foreach (var interaction in interactions)
        {
            var requirementPassed = CheckRequirements(user, target, interaction);
            if (!requirementPassed)
                continue;

            if (!InteractionMatchesSearch(interaction))
                continue;

            newInteractions.Add(interaction.ID);
        }

        newInteractions.Sort();

        // В Count мало смысла, но оптимизацию малость повысит.
        if (_currentInteractions.Count == newInteractions.Count && _currentInteractions.SequenceEqual(newInteractions))
        {
            return false;
        }

        _currentInteractions = newInteractions;
        return true;
    }

    private void ReloadInteractions(EntityUid user, EntityUid target)
    {
        ButtonsContainer.DisposeAllChildren();

        var categories = _prototypeManager.EnumeratePrototypes<PanelInteractionCategoryPrototype>();
        var interactions = _prototypeManager.EnumeratePrototypes<PanelInteractionPrototype>();

        foreach (var category in categories)
        {
            var categoryCollapsible = PrepareInteractionCategory(category);
            var categoryBody = new BoxContainer() { Orientation = LayoutOrientation.Vertical };

            foreach (var interaction in interactions.Where(i => i.Category.Id == category.ID).OrderBy(i => i.Name))
            {
                var requirementPassed = CheckRequirements(user, target, interaction);
                if (!requirementPassed)
                    continue;

                if (!InteractionMatchesSearch(interaction))
                    continue;

                if (user == target && interaction.SelfMessages.Count == 0)
                    continue;

                if (user != target && interaction.Messages.Count == 0)
                    continue;

                var interactionContainer = PrepareInteractionButton(interaction);
                categoryBody.AddChild(interactionContainer);
            }

            if (categoryBody.ChildCount == 0)
                continue;

            ButtonsContainer.AddChild(categoryCollapsible);
            categoryCollapsible.Body?.AddChild(categoryBody);
        }
    }

    private Collapsible PrepareInteractionCategory(PanelInteractionCategoryPrototype categoryProto)
    {
        var heading = new CollapsibleHeading(categoryProto.Name)
        {
            ChevronMargin = new Thickness(10, 0),
            MinHeight = 32,
        };

        heading.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = BackgroundColor,
            BorderColor = FrameColor,
            BorderThickness = new Thickness(0, 0, 0, 1),
        };

        var body = new CollapsibleBody();

        var category = new Collapsible(heading, body)
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 5)
        };

        heading.OnPressed += _ =>
        {
            category.BodyVisible = !category.BodyVisible;

            if (category.BodyVisible)
                _openedCategories.Add(categoryProto.Name);
            else
                _openedCategories.Remove(categoryProto.Name);
        };

        category.BodyVisible = _openedCategories.Contains(categoryProto.Name);

        return category;
    }

    private BoxContainer PrepareInteractionButton(PanelInteractionPrototype interaction)
    {
        var container = new BoxContainer();

        var button = new Button()
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 0),
            StyleClasses = { StyleBase.ButtonSquare },
            StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = ButtonColor,
                BorderColor = ButtonFrameColor,
                BorderThickness = new Thickness(2)
            }
        };

        button.OnPressed += _ => {
            OnSendEmote?.Invoke(interaction.ID,
                                CustomArousalButton.Pressed ? ArousalSlider.Value : 100f,
                                CustomMoaningButton.Pressed ? MoaningSlider.Value : 100f);
            _cooldowns[button] = (_timing.CurTime, interaction.Cooldown);
        };

        var icon = new TextureRect()
        {
            Texture = _sprite.Frame0(interaction.Icon),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Left,
        };

        var label = new Label()
        {
            Text = interaction.Name,
            Margin = new Thickness(40, 0, 0, 0)
        };

        button.AddChild(icon);
        button.AddChild(label);
        container.AddChild(button);

        return container;
    }

    private bool InteractionMatchesSearch(PanelInteractionPrototype interaction)
    {
        var searchText = SearchInput.Text.Trim();
        if (string.IsNullOrEmpty(searchText))
            return true;

        return interaction.Name.StartsWith(searchText, StringComparison.InvariantCultureIgnoreCase);
    }

    private bool CheckRequirements(EntityUid user, EntityUid target, PanelInteractionPrototype interaction)
    {
        var passed = true;

        if (IsErpInteraction(interaction) && !CanUseErp(user, target))
            return false;

        var transform = _entManager.System<TransformSystem>();
        if (!transform.InRange(user, target, interaction.Range))
            passed = false;

        if (interaction.UserRequirements != null)
        {
            foreach (var requirement in interaction.UserRequirements)
            {
                if (!requirement.IsAvailable(user, _entManager))
                    passed = false;
            }
        }

        if (interaction.TargetRequirements != null)
        {
            foreach (var requirement in interaction.TargetRequirements)
            {
                if (!requirement.IsAvailable(target, _entManager))
                    passed = false;
            }
        }

        return passed;
    }

    private bool IsErpInteraction(PanelInteractionPrototype interaction)
    {
        return interaction.Tags.Contains(ErpPanelConstants.ErpInteractionTag);
    }

    private bool CanUseErp(EntityUid user, EntityUid target)
    {
        if (_entManager.TryGetComponent<ErpStatusComponent>(user, out var userStatus) &&
            userStatus.Preference == ErpPreference.No)
            return false;

        if (user != target &&
            _entManager.TryGetComponent<ErpStatusComponent>(target, out var targetStatus) &&
            targetStatus.Preference == ErpPreference.No)
            return false;

        return true;
    }
}
