// SPDX-License-Identifier: MIT


using Robust.Client.UserInterface.CustomControls;
using Content.Client.Info;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared._CorvaxGoob.CCCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Player;
using Robust.Client.Console;
using Robust.Shared.Configuration;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Content.Client.Stylesheets;
using Robust.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Ghost;
using Content.Shared.Ghost;
using Content.Client.Ghost;
using Content.Client.UserInterface.Systems.Ghost;

namespace Content.Client.Options.UI
{

    [GenerateTypedNameReferences]
    public sealed partial class EscapeMenu : DefaultWindow
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IUriOpener _uriOpener = default!;
        [Dependency] private readonly IPlayerManager _playerManager = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        private void OpenDailyRewards()
        {
            _consoleHost.ExecuteCommand("dailyrewardmenu");
        }
        public EscapeMenu()
        {
            RobustXamlLoader.Load(this);
            AuthorizationDiscordButton.OnPressed += _ =>
            {
                var userId = _playerManager.LocalSession?.UserId;
                var requestUrl = $"{_cfg.GetCVar(CCCVars.DiscordAuthApiUrl)}/login/{userId.ToString()}";
                _uriOpener.OpenUri(new Uri(requestUrl));
            };

            Site.OnPressed += _ => _uriOpener.OpenUri(new Uri("https://ministation.ru"));
            Discord.OnPressed += _ => _uriOpener.OpenUri(new Uri("https://discord.gg/mini-station"));
            DailyRewardsButton.OnPressed += _ => OpenDailyRewards();
        }
    }
}
