// SPDX-License-Identifier: MIT


using Robust.Client.UserInterface.CustomControls;
using Content.Client._Mini.DiscordAuth;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Player;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI
{

    [GenerateTypedNameReferences]
    public sealed partial class EscapeMenu : DefaultWindow
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IUriOpener _uriOpener = default!;
        [Dependency] private readonly IPlayerManager _playerManager = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        private void OpenDailyRewards()
        {
            _consoleHost.ExecuteCommand("dailyrewardmenu");
        }
        public EscapeMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            AuthorizationDiscordButton.OnPressed += _ =>
                DiscordAuthLink.TryOpen(_cfg, _playerManager, _uriOpener);

            Site.OnPressed += _ => _uriOpener.OpenUri(new Uri("https://ministation.ru"));
            Discord.OnPressed += _ => _uriOpener.OpenUri(new Uri("https://discord.gg/mini-station"));
            DailyRewardsButton.OnPressed += _ => OpenDailyRewards();
        }
    }
}
