// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._CorvaxGoob.GhostBar.Controls;
using Content.Client._Mini.UserInterface.Systems.Ghost.Controls;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

    public MiniGhostTargetWindow TargetWindow { get; }
    private GhostBarRulesWindow? _ghostBarWindow;

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    public event Action? GhostBarPressed;
    public event Action? ReturnToRoundPressed; // FREAKY EDIT / Mini
    private int _prevImportantRoles;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TargetWindow = new MiniGhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => ClearImportantHighlight();
        GhostBarButton.OnPressed += _ => OpenGhostBarWindow();
        AntagTokensButton.OnPressed += _ => OpenAntagTokens(); // Mini-station
    }

    public void Hide()
    {
        TargetWindow.Close();
        _ghostBarWindow?.Close();
        Visible = false;
    }

    public void Update(int? roles, bool? canReturnToBody, bool? canTakeGhostRoles = true, int? importantRoles = null)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;
        GhostRolesButton.Disabled = !canTakeGhostRoles ?? true;

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            // Important = antagonists / ERT / CBURN — same red Caution style as changelog "new!".
            if (importantRoles is { } important && important > _prevImportantRoles)
                GhostRolesButton.StyleClasses.Add(StyleBase.ButtonCaution);

            if (importantRoles != null)
                _prevImportantRoles = importantRoles.Value;
        }

        TargetWindow.Populate();
    }

    private void ClearImportantHighlight()
    {
        GhostRolesButton.StyleClasses.Remove(StyleBase.ButtonCaution);
    }

    // Mini-station: hide ghost-role / antag / ghost bar during Typan war
    public void SetWarModeRestrictions(bool active)
    {
        GhostRolesButton.Visible = !active;
        AntagTokensButton.Visible = !active;
        GhostBarButton.Visible = !active;
    }

    private void OpenGhostBarWindow()
    {
        _ghostBarWindow ??= new GhostBarRulesWindow();
        _ghostBarWindow.SpawnButtonPressed -= OnGhostBarSpawnPressed;
        _ghostBarWindow.SpawnButtonPressed += OnGhostBarSpawnPressed;
        _ghostBarWindow.OpenCentered();
    }

    private void OnGhostBarSpawnPressed()
    {
        GhostBarPressed?.Invoke();
        _ghostBarWindow?.Close();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
            if (_ghostBarWindow != null)
            {
                _ghostBarWindow.SpawnButtonPressed -= OnGhostBarSpawnPressed;
                _ghostBarWindow.Dispose();
                _ghostBarWindow = null;
            }
        }
    }

    private void OpenAntagTokens()
    {
        _consoleHost.ExecuteCommand("antagtokenmenu");
    }
}
