// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._Mini.UserInterface.Systems.Ghost.Controls;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

    public MiniGhostTargetWindow TargetWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    public event Action? ThunderdomePressed; // Goobstation - Thunderdome
    public event Action? ReturnToRoundPressed; // FREAKY EDIT / Mini
    private int _prevNumberRoles;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TargetWindow = new MiniGhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleClass.Negative);
        ThunderdomeButton.OnPressed += _ => ThunderdomePressed?.Invoke(); // Goobstation - Thunderdome
        AntagTokensButton.OnPressed += _ => OpenAntagTokens(); // Mini-station
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    public void Update(int? roles, bool? canReturnToBody, bool? canTakeGhostRoles = true)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;
        GhostRolesButton.Disabled = !canTakeGhostRoles ?? true;

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleClass.Negative);
            }

            _prevNumberRoles = (int)roles;
        }

        TargetWindow.Populate();
    }

    // Mini-station: hide ghost-role / antag / thunderdome during Typan war
    public void SetWarModeRestrictions(bool active)
    {
        GhostRolesButton.Visible = !active;
        AntagTokensButton.Visible = !active;
        ThunderdomeButton.Visible = !active;
    }

    // Goobstation - Thunderdome
    public void UpdateThunderdome(int playerCount)
    {
        ThunderdomeButton.Text = Loc.GetString("thunderdome-ghost-button", ("count", playerCount));
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }

    private void OpenAntagTokens()
    {
        _consoleHost.ExecuteCommand("antagtokenmenu");
    }
}
