# SPDX-License-Identifier: MIT

contact_links:
  - name: Сообщить о нарушениях безопасности / Report a Security Vulnerability
    url: https://github.com/space-wizards/space-station-14/blob/master/SECURITY.md
    about: Пожалуйста, сообщите о нарушениях безопасности в частном порядке, чтобы мы могли исправить их до того, как они станут общедоступными. / Please report security vulnerabilities privately so we can fix them before they are publicly disclosed
