# SPDX-License-Identifier: AGPL-3.0-or-later

# Default pool = Mini copies of CorvaxGoob stations (+ MiniSilly)
- type: gameMapPool
  id: DefaultMapPool
  maps:
  # Highpop 55+
  - MiniAstra
  #- MiniAvrite
  - MiniBox
  - MiniChloris
  - MiniDelta
  - MiniGlacier
  - MiniPilgrim

  # Midpop 25–55
  # - MiniAmber
  - MiniBagel
  #- MiniMarathon
  - MiniMascara
  - MiniOutpost
  - MiniPaper
  #- MiniPearl
  - MiniVoid

  # Lowpop 0–25
  #- MiniMaus
  - MiniOmega
  - MiniPacked
  - MiniSilly
  # - MiniTushkan
  - MiniCluster
