# SPDX-License-Identifier: AGPL-3.0-or-later

- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#9E6A34" # Mini edit
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - ShaftMiner # Lavaland Change
  - Bitrunner # Orion

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#4e7c22" # Mini edit
  weight: -10
  roles:
  - Bartender
  - Botanist
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  #- Lawyer #Corvax Goob Legal Department
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - ServiceWorker
  - PartyMaker # event-restricted, Goobstation

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  roles:
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - HecuOperative
  - BlueshieldOfficer # Goobstation - Start
  - NanotrasenRepresentative
  - NanotrasenCareerTrainer
  - NavyOfficer
  - NavyCaptain
  - NavyOfficerUndercover
  - SpecialOperationsOfficer
  - Diplomat
  - GovernmentMan # Goobstation - End
  editorHidden: true
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - BlueshieldOfficer # Goobstation
  - NanotrasenRepresentative # Goobstation
  - NanotrasenCareerTrainer # Goobstation
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - HecuOperative
  - CommandMaid # event-restricted, Goobstation
  primary: false
  weight: 100

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  weight: 10  # Mini-weights
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#3b627a" # Mini edit
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - Geneticist # Mini: Paradise/Wega genetics
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - Surgeon # CorvaxGoob-Surgeon
  - Virologist # Gooby goob ba gooby goob ba

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#770101" # Mini edit
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden
  - Brigmedic # Goob
  - Pilot # Corvax-Pilot
  - WardenHelper # CorvaxGoob-WardenHelper
  - SecurityClown # event-restricted, Goob

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#984EB4" # Mini edit
  roles:
  - ResearchDirector
  - Scientist
  - ResearchAssistant
  - Roboticist #Goob

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#61738d" # Mini edit
  roles:
  - Borg
  - StationAi

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 5  # Mini-weights
  roles:
  - RadioHost # Goobstation
  - Reporter
  - Psychologist
  primary: false
