- type: job
  id: TypanOfficer
  name: job-name-typan-officer
  playTimeTracker: TypanOfficer
  description: job-description-typan-officer
  startingGear: TypanOfficer
  icon: "JobIconSyndicateOfficer"
  supervisors: job-supervisors-typan-syndicate
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200
    - !type:DepartmentTimeRequirement
      department: Command
      time: 7200
    - !type:DepartmentTimeRequirement
      department: Security
      time: 14400
    - !type:OverallPlaytimeRequirement
      time: 21600
    - !type:AgeRequirement
      requiredAge: 26
  access:
  - TypanArmory
  - TypanCommand
  - TypanCommunicationsOfficer
  - TypanEngineering
  - TypanMaint
  - TypanProtection
  - TypanScience
  - TypanService
  - TypanVault
  - TypanExternal
  - SyndicateAgent
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skills # Corvax-Next-Skills
        skills:
        - ShuttleControl
        - Shooting

- type: startingGear
  id: TypanOfficer
  equipment:
    ears: ClothingHeadsetAltSyndicate
    shoes: ClothingShoesBootsCombat
    jumpsuit: ClothingUniformJumpsuitOperative
    gloves: ClothingHandsGlovesCombat
    id: SyndiPDAOff
    head: ClothingHeadHatSyndie
    pocket1: WeaponPistolViper
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudTypan
    outerClothing: ClothingOuterWinterSyndieCapArmored
  storage:
    back:
    - MagazinePistolIncendiary
    - MagazinePistolIncendiary
    - Stunprod
    - Zipties
    - Zipties
    - SurvivalMedipen

