- type: job
  id: TypanTechnicalOperationsSupervisor
  name: job-name-typan-technical-supervisor
  description: job-description-typan-technical-supervisor
  playTimeTracker: JobTypanTechnicalOperationsSupervisor
  setPreference: true
  startingGear: TypanTechnicalOperationsSupervisorGear
  icon: "JobIconTypanTechnicalOperationsSupervisor"
  supervisors: job-supervisors-typan-syndicate
  canBeAntag: false
  weight: 10
  requirements:
  - !type:RoleTimeRequirement
    role: JobTypanAtmosTech
    time: 54000 # 15 hours
  access:
  - TypanAtmospherics
  - TypanCargo
  - TypanCommand
  - TypanEngineering
  - TypanMaint
  - TypanMedical
  - TypanResearch
  - TypanService
  - TypanTechnicalOperationsSupervisor
  - TypanExternal
  - SyndicateAgent
  skills: # CorvaxGoob-Skills
  - Shooting
  - ShuttleControl
  - AdvancedBuilding
  - MedicalEquipment
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTypan ]
  - !type:AddComponentSpecial
    components:
      - type: AntagImmune
      - type: NpcFactionMember
        factions:
        - Typan

- type: startingGear
  id: TypanTechnicalOperationsSupervisorGear
  equipment:
    ears: ClothingHeadsetAltSyndicate
    id: SyndiPDATOS

- type: chameleonOutfit
  id: TypanTechnicalOperationsSupervisorChameleonOutfit
  job: TypanTechnicalOperationsSupervisor
  startingGear: TypanTechnicalOperationsSupervisorGear
