using System;
using System.Numerics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Client.ResourceManagement;
using Robust.Client.Graphics;
using Robust.Shared.Log;
using Content.Shared._Amour.Stickers;

namespace Content.Client._Amour.Stickers.UI;

[GenerateTypedNameReferences]
public sealed partial class StickerSelectorWindow : DefaultWindow
{
    private static StickerSelectorWindow? _instance;
    
    public event Action<StickerPrototype>? OnStickerSelected;
    
    private readonly StickerSystem _stickerSystem;

    private StickerSelectorWindow()
    {
        RobustXamlLoader.Load(this);
        
        _stickerSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<StickerSystem>();
        
        PopulateStickers();
        
        OnClose += () =>
        {
            ClearHandlers();
        };
    }
    
    public static StickerSelectorWindow GetInstance()
    {
        if (_instance == null || _instance.Disposed)
        {
            _instance = new StickerSelectorWindow();
        }
        
        return _instance;
    }
    
    public void ClearHandlers()
    {
        OnStickerSelected = null;
    }

    private void PopulateStickers()
    {
        StickerGrid.Children.Clear();
        
        var stickers = _stickerSystem.GetStickers();
        var resCache = IoCManager.Resolve<IResourceCache>();

        foreach (var sticker in stickers)
        {
            Texture texture;
            try
            {
                texture = resCache.GetResource<TextureResource>(sticker.TexturePath).Texture;
            }
            catch (Exception ex)
            {
                Logger.ErrorS("stickers", $"Failed to load sticker texture {sticker.ID}: {ex.Message}");
                continue;
            }

            var isMiniEmoji = sticker.TexturePath.ToString()
                .Contains("_Mini/Interface/Emoji", StringComparison.OrdinalIgnoreCase);
            var iconSize = isMiniEmoji ? 36f / 1.5f : 36f; // ~24 for Mini
            var btnSize = isMiniEmoji ? 48f / 1.5f : 48f;

            var btn = new Button
            {
                MinSize = new Vector2(btnSize, btnSize),
                MaxSize = new Vector2(btnSize + 8f, btnSize + 8f),
                ToolTip = sticker.ID
            };

            var texRect = new TextureRect
            {
                Texture = texture,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = Control.HAlignment.Center,
                VerticalAlignment = Control.VAlignment.Center,
                SetSize = new Vector2(iconSize, iconSize),
                MinSize = new Vector2(iconSize, iconSize),
                MaxSize = new Vector2(iconSize, iconSize)
            };

            btn.AddChild(texRect);
            btn.OnPressed += _ => 
            {
                OnStickerSelected?.Invoke(sticker);
                Close();
            };
            
            StickerGrid.AddChild(btn);
        }
    }
}
