using System;
using System.Numerics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Client.ResourceManagement;
using Robust.Client.Graphics;
using Robust.Shared.Log;
using Content.Shared._Amour.Stickers;

namespace Content.Client._Amour.Stickers.UI;

[GenerateTypedNameReferences]
public sealed partial class StickerSelectorWindow : DefaultWindow
{
    private const float CellSize = 40f;
    private const float IconSize = 32f;
    private const float GridMargin = 8f;

    private static StickerSelectorWindow? _instance;

    public event Action<StickerPrototype>? OnStickerSelected;

    private readonly StickerSystem _stickerSystem;

    private StickerSelectorWindow()
    {
        RobustXamlLoader.Load(this);

        _stickerSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<StickerSystem>();

        PopulateStickers();
        StickerScroll.OnResized += UpdateColumns;
        UpdateColumns();

        OnClose += () =>
        {
            ClearHandlers();
        };
    }

    public static StickerSelectorWindow GetInstance()
    {
        if (_instance == null || _instance.Disposed)
        {
            _instance = new StickerSelectorWindow();
        }

        return _instance;
    }

    public void ClearHandlers()
    {
        OnStickerSelected = null;
    }

    private void UpdateColumns()
    {
        // Keep cells perfectly square and the grid evenly filled: one column per ~40px of width.
        var available = StickerScroll.Width - GridMargin;
        if (available < CellSize)
            return;

        var columns = Math.Max(1, (int) (available / (CellSize + 2f)));
        if (StickerGrid.Columns != columns)
            StickerGrid.Columns = columns;
    }

    private void PopulateStickers()
    {
        StickerGrid.Children.Clear();

        var stickers = _stickerSystem.GetStickers();
        var resCache = IoCManager.Resolve<IResourceCache>();

        foreach (var sticker in stickers)
        {
            Texture texture;
            try
            {
                texture = resCache.GetResource<TextureResource>(sticker.TexturePath).Texture;
            }
            catch (Exception ex)
            {
                Logger.ErrorS("stickers", $"Failed to load sticker texture {sticker.ID}: {ex.Message}");
                continue;
            }

            // Uniform square cells for everything: mixed emoji/sticker sizes were making the
            // grid ragged (columns sized by the tallest cell in each column).
            var btn = new Button
            {
                MinSize = new Vector2(CellSize, CellSize),
                MaxSize = new Vector2(CellSize, CellSize),
                ToolTip = sticker.ID
            };

            var texRect = new TextureRect
            {
                Texture = texture,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = Control.HAlignment.Center,
                VerticalAlignment = Control.VAlignment.Center,
                SetSize = new Vector2(IconSize, IconSize)
            };

            btn.AddChild(texRect);
            btn.OnPressed += _ =>
            {
                OnStickerSelected?.Invoke(sticker);
                Close();
            };

            StickerGrid.AddChild(btn);
        }
    }
}
