// MIT License

// Copyright (c) 2026 Vecortys (vecortys@gmail.com)

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Arcane.CCVars;
using Content.Shared._Arcane.InfinityDorm;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client._Arcane.InfinityDorm;

[GenerateTypedNameReferences]
public sealed partial class InfinityDormTeleporterWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public string SelectedRoom = string.Empty;
    public int SelectedNumber = 0;

    public Action? ConfirmPressed;

    public InfinityDormTeleporterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ReloadRooms();
        _proto.PrototypesReloaded += OnProtoReload;

        NumberInput.OnTextChanged += args => ValidateDormNumber(args.Text);

        Confirm.OnPressed += _ => ConfirmPressed?.Invoke();

        SetRoomsAvailable(0);
    }

    public override void Close()
    {
        base.Close();

        _proto.PrototypesReloaded -= OnProtoReload;
    }

    public void SetRoomsAvailable(int available)
    {
        RoomsAvailable.Text = $"{available}/{_cfg.GetCVar(ACCVars.MaxUserInfinityDorms)}";
    }

    private void OnProtoReload(PrototypesReloadedEventArgs args)
    {
        if (!args.WasModified<InfinityDormPrototype>() && !args.WasModified<InfinityDormCategoryPrototype>())
            return;

        ReloadRooms();
    }

    private void ReloadRooms()
    {
        if (Disposed)
            return;

        RoomsContainer.RemoveAllChildren();

        var rooms = _proto.EnumeratePrototypes<InfinityDormPrototype>();

        foreach (var room in rooms.OrderBy(r => _proto.Index<InfinityDormCategoryPrototype>(r.Category.Id).Priority))
        {
            var category = _proto.Index<InfinityDormCategoryPrototype>(room.Category.Id);

            var roomButton = new Button()
            {
                Name = room.ID,
                Text = Loc.GetString("infinity-dorm-name", ("category", category.Name), ("name", room.Title)),
                ToolTip = Loc.GetString("infinity-dorm-desc", ("desc", room.Description), ("author", room.Author)),
                ModulateSelfOverride = category.Color,
                Margin = new Thickness(0, 0, 0, 3)
            };
            roomButton.OnPressed += args => OnPressedRoomButton(args);

            RoomsContainer.AddChild(roomButton);
        }
    }

    private void OnPressedRoomButton(ButtonEventArgs args)
    {
        if (args.Button.Name is null || !_proto.TryIndex<InfinityDormPrototype>(args.Button.Name, out var prototype))
            return;

        SelectedRoom = prototype.ID;
        CurrentRoom.Text = prototype.Title;
    }

    private void ValidateDormNumber(string text)
    {
        if (!int.TryParse(text, out var newNumber))
            return;

        NumberInput.Text = newNumber.ToString();
        SelectedNumber = newNumber;
    }
}
