# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: true
  whitelisted: true
  startingGear: CentcomGear
  icon: "JobIconCentCommOfficial"
  supervisors: job-supervisors-centcom # Goobstation
  canBeAntag: false
  skills: # CorvaxGoob-Skills
  - All
  guides: # Mini
  - CentralCommandOfficial
  - Writing
  - SOPCentcomm
  weight: 40 # Top of CentComm prefs list (ПЦК)

  requirements:
  - !type:AgeRequirement
    requiredAge: 21
  - !type:SpeciesRequirement # Goob - None Felinid
    inverted: true
    species:
    - Felinid
  - !type:SpeciesRequirement # CorvaxGoob-Species
    inverted: true
    species:
    - Abductor
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]

# Unique kit only — clothes come from JobCentralCommandOfficial roleLoadout groups.
- type: startingGear
  id: CentcomGear
  equipment:
    outerClothing: ClothingOuterArmorCentcommCarapace
    eyes: ClothingEyesGlassesCentComm
    neck: ExecutiveIDCard
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltHolsterFilledCentComm
    pocket1: BoxFolderCentCom
    pocket2: WeaponDisablerAdvanced
  storage:
    back:
    - HandheldFaxOfficial
    - BoxFolderCentComClipboard
    - DeterrentCaseFilled
    - DoorRemoteAll
    - TelephoneCentComm

- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
