- type: job
  id: FieldCommander
  name: Полевой командир
  description: Вести своих морпехов на планете к ужасной и неизбежной, но славной смерти. В том числе своей.
  playTimeTracker: JobFieldCommander
  startingGear: FieldCommanderGearUGE
  icon: "JobIconFieldCommander"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-head-operations
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
#  access:
#  - StaffOfficerUGE
  accessGroups:
  - StaffOfficerUGE


- type: startingGear
  id: FieldCommanderGearUGE
  equipment:
    head: ClothingHeadCapFieldCommander
    outerClothing: CMArmorField_commander
    gloves: ClothingHandsField
    jumpsuit: UGEJumpsuitFieldСommander
    eyes: ClothingEyesGlassesRPG
    id: FieldCommanderIDCard
    ears: ClothingHeadsetAltCommand
    back: ClothingBackpackMilitarySatchel
    mask: CMMaskGasFieldСommander
    belt: RMCFieldBeltHolster
    shoes: CMBootsBlack
    pocket1: RMCPouchLargeDrop
    pocket2: RMCPouchСommand
