// SPDX-FileCopyrightText: 2022 E F R <602406+Efruit@users.noreply.github.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Content.Client._Amour.Stickers.UI;
using System.Numerics;

namespace Content.Client.Administration.UI.Bwoink
{
    [GenerateTypedNameReferences]
    public sealed partial class BwoinkPanel : BoxContainer
    {
        private readonly Action<string> _messageSender;

        public int Unread { get; private set; } = 0;
        public DateTime LastMessage { get; private set; } = DateTime.MinValue;
        private List<string> PeopleTyping { get; set; } = new();
        private bool _introShown;
        public event Action<string>? InputTextChanged;

        public BwoinkPanel(Action<string> messageSender)
        {
            RobustXamlLoader.Load(this);

            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);
            msg.AddText(Loc.GetString("bwoink-system-messages-being-relayed-to-discord"));
            msg.Pop();
            RelayedToDiscordLabel.SetMessage(msg);

            _messageSender = messageSender;

            // Mini edit: the actionSearchBox texture was almost invisible on the dark ahelp panel;
            // give the input a proper dark background with a readable border instead.
            var senderBox = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#14141C"),
                BorderColor = Color.FromHex("#45455C"),
                BorderThickness = new Thickness(1),
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
            };
            SenderLineEdit.StyleBoxOverride = senderBox;

            OnVisibilityChanged += c =>
            {
                if (c.Visible)
                    Unread = 0;
            };
            SenderLineEdit.OnTextEntered += Input_OnTextEntered;
            SenderLineEdit.OnTextChanged += Input_OnTextChanged;

            // Amour edit start
            StickerBtn.OnStickerSelected += sticker => StickerInputHelper.InsertSticker(SenderLineEdit, sticker);
            // Amour edit end

            UpdateTypingIndicator();
            UiChatFonts.ApplyToOutput(TextOutput);
        }

        public void RefreshOutputFont() => UiChatFonts.ApplyToOutput(TextOutput);

        public void AttachRatingPanel(AHelpRatingPanel panel)
        {
            RatingHost.DisposeAllChildren();
            RatingHost.AddChild(panel);
        }

        private void Input_OnTextEntered(LineEdit.LineEditEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(args.Text))
                return;

            _messageSender.Invoke(args.Text);
            SenderLineEdit.Clear();
        }

        private void Input_OnTextChanged(LineEdit.LineEditEventArgs args)
        {
            InputTextChanged?.Invoke(args.Text);
        }

        public void ShowIntroductoryMessageIfNeeded()
        {
            if (_introShown)
                return;

            _introShown = true;

            var formatted = new FormattedMessage();
            formatted.PushColor(Color.LightGray);
            formatted.AddText(Loc.GetString("bwoink-system-introductory-message"));
            formatted.Pop();
            TextOutput.AddMessage(formatted);
        }

        public void ReceiveLine(SharedBwoinkSystem.BwoinkTextMessage message)
        {
            if (!Visible)
                Unread++;

            var formatted = new FormattedMessage(1);
            var markup = $"[color=gray]{message.SentAt.ToShortTimeString()}[/color] {message.Text}";
            if (!formatted.TryAddMarkup(markup, out _))
                formatted.AddMarkupPermissive(markup);
            TextOutput.AddMessage(formatted);
            LastMessage = message.SentAt;
        }

        private void UpdateTypingIndicator()
        {
            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);

            var text = PeopleTyping.Count == 0
                ? string.Empty
                : Loc.GetString("bwoink-system-typing-indicator",
                    ("players", string.Join(", ", PeopleTyping)),
                    ("count", PeopleTyping.Count));

            msg.AddText(text);
            msg.Pop();

            TypingIndicator.SetMessage(msg);
        }

        public void UpdatePlayerTyping(string name, bool typing)
        {
            if (typing)
            {
                if (PeopleTyping.Contains(name))
                    return;

                PeopleTyping.Add(name);
                Timer.Spawn(TimeSpan.FromSeconds(10), () =>
                {
                    if (Disposed)
                        return;

                    PeopleTyping.Remove(name);
                    UpdateTypingIndicator();
                });
            }
            else
            {
                PeopleTyping.Remove(name);
            }

            UpdateTypingIndicator();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            InputTextChanged = null;
        }
    }
}
