// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Numerics;
using Content.Client.Guidebook;
using Content.Client.Guidebook.Components;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.UserInterface.Controls
{
    [GenerateTypedNameReferences]
    [Virtual]
    public partial class FancyWindow : BaseWindow
    {
        [Dependency] private readonly IEntitySystemManager _sysMan = default!;
        [Dependency] private readonly IStylesheetManager _styleMan = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        [Dependency] private readonly IGameTiming _timing = default!;
        private GuidebookSystem? _guidebookSystem;
        private const int DRAG_MARGIN_SIZE = 7;
        private Color _accentColor = Color.FromHex("#4A90D9");

        public const string StyleClassWindowHelpButton = "windowHelpButton";
        public const string StyleClassWindowCloseButton = "windowCloseButton";

        public FancyWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            CloseButton.OnPressed += _ => Close();
            HelpButton.OnPressed += _ => Help();
            XamlChildren = ContentsContainer.Children;
            RefreshAccentColor();
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            _styleMan.StylesheetsUpdated += OnStylesheetsUpdated;
            RefreshAccentColor();
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();
            _styleMan.StylesheetsUpdated -= OnStylesheetsUpdated;
        }

        private void OnStylesheetsUpdated()
        {
            RefreshAccentColor();
        }

        private void RefreshAccentColor()
        {
            _accentColor = new Color(
                (byte) _cfg.GetCVar(CCVars.InterfaceAccentRed),
                (byte) _cfg.GetCVar(CCVars.InterfaceAccentGreen),
                (byte) _cfg.GetCVar(CCVars.InterfaceAccentBlue));
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            // Soft "signal" pulse on the accent rail — Mini identity without neon spam.
            var pulse = 0.62f + 0.38f * (0.5f + 0.5f * MathF.Sin((float) _timing.RealTime.TotalSeconds * 1.55f));
            AccentRail.ModulateSelfOverride = _accentColor.WithAlpha(pulse);
        }

        public string? Title
        {
            get => WindowTitle.Text;
            set => WindowTitle.Text = value;
        }

        private string? _stylesheet;

        public new string? Stylesheet
        {
            get => _stylesheet;
            set
            {
                _stylesheet = value;
                if (value is not null && _styleMan.TryGetStylesheet(value, out var stylesheet))
                    base.Stylesheet = stylesheet;
            }
        }

        private List<ProtoId<GuideEntryPrototype>>? _helpGuidebookIds;

        public List<ProtoId<GuideEntryPrototype>>? HelpGuidebookIds
        {
            get => _helpGuidebookIds;
            set
            {
                _helpGuidebookIds = value;
                HelpButton.Disabled = _helpGuidebookIds == null;
                HelpButton.Visible = !HelpButton.Disabled;
            }
        }

        public void Help()
        {
            if (HelpGuidebookIds is null)
                return;
            _guidebookSystem ??= _sysMan.GetEntitySystem<GuidebookSystem>();
            _guidebookSystem.OpenHelp(HelpGuidebookIds);
        }

        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            var mode = DragMode.Move;

            if (Resizable)
            {
                if (relativeMousePos.Y < DRAG_MARGIN_SIZE)
                {
                    mode = DragMode.Top;
                }
                else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE)
                {
                    mode = DragMode.Bottom;
                }

                if (relativeMousePos.X < DRAG_MARGIN_SIZE)
                {
                    mode |= DragMode.Left;
                }
                else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE)
                {
                    mode |= DragMode.Right;
                }
            }

            return mode;
        }

        public string HeaderClass { set => WindowHeader.SetOnlyStyleClass(value); }
        public string TitleClass { set => WindowTitle.SetOnlyStyleClass(value); }
    }

    /// <summary>
    /// Helper functions for working with <see cref="FancyWindow"/>.
    /// </summary>
    public static class FancyWindowExt
    {
        /// <summary>
        /// Sets information for a window (title and guidebooks) based on an entity.
        /// </summary>
        /// <param name="window">The window to modify.</param>
        /// <param name="entityManager">Entity manager used to retrieve the information.</param>
        /// <param name="entity">The entity that this window represents.</param>
        /// <seealso cref="SetTitleFromEntity"/>
        /// <seealso cref="SetGuidebookFromEntity"/>
        public static void SetInfoFromEntity(this FancyWindow window, IEntityManager entityManager, EntityUid entity)
        {
            window.SetTitleFromEntity(entityManager, entity);
            window.SetGuidebookFromEntity(entityManager, entity);
        }

        /// <summary>
        /// Set a window's title to the name of an entity.
        /// </summary>
        /// <param name="window">The window to modify.</param>
        /// <param name="entityManager">Entity manager used to retrieve the information.</param>
        /// <param name="entity">The entity that this window represents.</param>
        /// <seealso cref="SetInfoFromEntity"/>
        public static void SetTitleFromEntity(
            this FancyWindow window,
            IEntityManager entityManager,
            EntityUid entity)
        {
            window.Title = entityManager.GetComponent<MetaDataComponent>(entity).EntityName;
        }

        /// <summary>
        /// Set a window's guidebook IDs to those of an entity.
        /// </summary>
        /// <param name="window">The window to modify.</param>
        /// <param name="entityManager">Entity manager used to retrieve the information.</param>
        /// <param name="entity">The entity that this window represents.</param>
        /// <seealso cref="SetInfoFromEntity"/>
        public static void SetGuidebookFromEntity(
            this FancyWindow window,
            IEntityManager entityManager,
            EntityUid entity)
        {
            window.HelpGuidebookIds = entityManager.GetComponentOrNull<GuideHelpComponent>(entity)?.Guides;
        }
    }
}
