// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Flipp Syder <76629141+vulppine@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Moony <moony@hellomouse.net>
// SPDX-FileCopyrightText: 2023 TemporalOroboros <TemporalOroboros@gmail.com>
// SPDX-FileCopyrightText: 2023 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 moonheart08 <moonheart08@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 SlamBamActionman <83650252+SlamBamActionman@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 beck-thompson <107373427+beck-thompson@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 c4llv07e <38111072+c4llv07e@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2025 BombasterDS2 <shvalovdenis.workmail@gmail.com>
// SPDX-FileCopyrightText: 2025 gus <august.eymann@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.CCVar;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using static Content.Shared.Access.Components.IdCardConsoleComponent;

namespace Content.Client.Access.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class IdCardConsoleWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfgManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly ILogManager _logManager = default!;
        private readonly ISawmill _logMill = default!;

        private readonly IdCardConsoleBoundUserInterface _owner;

        // CCVar.
        private int _maxNameLength;
        private int _maxIdJobLength;

        private AccessLevelControl _accessButtons = new();
        private readonly List<string> _jobPrototypeIds = new();
        private readonly HashSet<ProtoId<AccessLevelPrototype>> _allowedModifyAccess = new();
        private readonly HashSet<ProtoId<AccessLevelPrototype>> _extendedAccessExclusions = new();

        private string? _lastFullName;
        private string? _lastJobTitle;
        private string? _lastJobProto;

        // The job that will be picked if the ID doesn't have a job on the station.
        private static ProtoId<JobPrototype> _defaultJob = "Passenger";

        public IdCardConsoleWindow(IdCardConsoleBoundUserInterface owner,
            IPrototypeManager prototypeManager,
            List<ProtoId<AccessLevelPrototype>> accessLevels,
            bool showFullAccessButton,
            bool showExtendedAccessButton,
            List<ProtoId<AccessLevelPrototype>> extendedAccessExclusions)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _logMill = _logManager.GetSawmill(SharedIdCardConsoleSystem.Sawmill);

            _owner = owner;

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);

            FullNameLineEdit.OnTextEntered += _ => SubmitData();
            FullNameLineEdit.IsValid = s => s.Length <= _maxNameLength;
            FullNameLineEdit.OnTextChanged += _ =>
            {
                FullNameSaveButton.Disabled = FullNameSaveButton.Text == _lastFullName;
            };
            FullNameSaveButton.OnPressed += _ => SubmitData();

            JobTitleLineEdit.OnTextEntered += _ => SubmitData();
            JobTitleLineEdit.IsValid = s => s.Length <= _maxIdJobLength;
            JobTitleLineEdit.OnTextChanged += _ =>
            {
                JobTitleSaveButton.Disabled = JobTitleLineEdit.Text == _lastJobTitle;
            };
            JobTitleSaveButton.OnPressed += _ => SubmitData();
            // Goobstation Start
            SearchLineEdit.OnTextChanged += args =>
            {
                var query = args.Text.Trim();
                var containerChild = AccessLevelControlContainer.GetChild(0);
                containerChild.RemoveAllChildren();

                if (string.IsNullOrEmpty(query))
                {
                    foreach (var button in _accessButtons.ButtonsList.Values)
                        containerChild.AddChild(button);
                    return;
                }

                foreach (var (id, button) in _accessButtons.ButtonsList)
                    if (id.Id.Contains(query, StringComparison.CurrentCultureIgnoreCase))
                        containerChild.AddChild(button);
            };
            // Goobstation End

            var jobs = _prototypeManager.EnumeratePrototypes<JobPrototype>().ToList();
            jobs.Sort((x, y) => string.Compare(x.LocalizedName, y.LocalizedName, StringComparison.CurrentCulture));

            foreach (var job in jobs)
            {
                if (!job.OverrideConsoleVisibility.GetValueOrDefault(job.SetPreference))
                {
                    continue;
                }

                _jobPrototypeIds.Add(job.ID);
                JobPresetOptionButton.AddItem(Loc.GetString(job.Name), _jobPrototypeIds.Count - 1);
            }

            JobPresetOptionButton.OnItemSelected += SelectJobPreset;
            ApplyJobAccessButton.OnPressed += _ => ApplyCurrentJobPresetAccesses();
            _accessButtons.Populate(accessLevels, prototypeManager);
            AccessLevelControlContainer.AddChild(_accessButtons);
            AccessPresetButtonsContainer.Visible = showFullAccessButton || showExtendedAccessButton;
            FullAccessButton.Visible = showFullAccessButton;
            ExtendedAccessButton.Visible = showExtendedAccessButton;
            FullAccessButton.OnPressed += _ => ApplyAccessPreset(fullAccess: true);
            ExtendedAccessButton.OnPressed += _ => ApplyAccessPreset(fullAccess: false);

            foreach (var access in extendedAccessExclusions)
            {
                _extendedAccessExclusions.Add(access);
            }

            foreach (var (id, button) in _accessButtons.ButtonsList)
            {
                button.OnPressed += _ => SubmitData();
            }
        }

        private void ClearAllAccess()
        {
            foreach (var button in _accessButtons.ButtonsList.Values)
            {
                if (button.Pressed)
                {
                    button.Pressed = false;
                }
            }
        }

        private void SelectJobPreset(OptionButton.ItemSelectedEventArgs args)
        {
            args.Button.SelectId(args.Id);
            ApplyCurrentJobPresetAccesses();
        }

        private void ApplyCurrentJobPresetAccesses()
        {
            if (JobPresetOptionButton.SelectedId < 0 ||
                JobPresetOptionButton.SelectedId >= _jobPrototypeIds.Count)
            {
                return;
            }

            var selectedJob = _jobPrototypeIds[JobPresetOptionButton.SelectedId];
            if (!_prototypeManager.TryIndex(selectedJob, out JobPrototype? job))
            {
                return;
            }

            JobTitleLineEdit.Text = Loc.GetString(job.Name);
            var jobAccesses = new HashSet<ProtoId<AccessLevelPrototype>>();
            foreach (var access in job.Access)
            {
                jobAccesses.Add(access);
            }

            foreach (var group in job.AccessGroups)
            {
                if (!_prototypeManager.TryIndex(group, out AccessGroupPrototype? groupPrototype))
                    continue;

                foreach (var access in groupPrototype.Tags)
                {
                    jobAccesses.Add(access);
                }
            }

            foreach (var (accessId, button) in _accessButtons.ButtonsList)
            {
                button.Pressed = !button.Disabled && jobAccesses.Contains(accessId);
            }

            SubmitData();
        }

        private void ApplyAccessPreset(bool fullAccess)
        {
            ClearAllAccess();

            foreach (var (id, button) in _accessButtons.ButtonsList)
            {
                if (button.Disabled || !_allowedModifyAccess.Contains(id))
                    continue;

                if (!fullAccess && _extendedAccessExclusions.Contains(id))
                    continue;

                button.Pressed = true;
            }

            SubmitData();
        }

        public void UpdateState(IdCardConsoleBoundUserInterfaceState state)
        {
            PrivilegedIdButton.Text = state.IsPrivilegedIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            PrivilegedIdLabel.Text = state.PrivilegedIdName;

            TargetIdButton.Text = state.IsTargetIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            TargetIdLabel.Text = state.TargetIdName;

            var interfaceEnabled =
                state.IsPrivilegedIdPresent && state.IsPrivilegedIdAuthorized && state.IsTargetIdPresent;

            var fullNameDirty = _lastFullName != null && FullNameLineEdit.Text != state.TargetIdFullName;
            var jobTitleDirty = _lastJobTitle != null && JobTitleLineEdit.Text != state.TargetIdJobTitle;

            FullNameLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
            FullNameLineEdit.Editable = interfaceEnabled;
            if (!fullNameDirty)
            {
                FullNameLineEdit.Text = state.TargetIdFullName ?? string.Empty;
            }

            FullNameSaveButton.Disabled = !interfaceEnabled || !fullNameDirty;

            JobTitleLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
            JobTitleLineEdit.Editable = interfaceEnabled;
            if (!jobTitleDirty)
            {
                JobTitleLineEdit.Text = state.TargetIdJobTitle ?? string.Empty;
            }

            JobTitleSaveButton.Disabled = !interfaceEnabled || !jobTitleDirty;

            JobPresetOptionButton.Disabled = !interfaceEnabled;
            ApplyJobAccessButton.Disabled = !interfaceEnabled;

            _accessButtons.UpdateState(state.TargetIdAccessList?.ToList() ??
                                       new List<ProtoId<AccessLevelPrototype>>(),
                                       state.AllowedModifyAccessList?.ToList() ??
                                       new List<ProtoId<AccessLevelPrototype>>());

            _allowedModifyAccess.Clear();
            if (state.AllowedModifyAccessList != null)
            {
                foreach (var access in state.AllowedModifyAccessList)
                {
                    _allowedModifyAccess.Add(access);
                }
            }

            var canUsePresetButtons = interfaceEnabled && _allowedModifyAccess.Count > 0;
            FullAccessButton.Disabled = !canUsePresetButtons;
            ExtendedAccessButton.Disabled = !canUsePresetButtons;

            var jobIndex = _jobPrototypeIds.IndexOf(state.TargetIdJobPrototype);
            // If the job index is < 0 that means they don't have a job registered in the station records
            // or the IdCardComponent's JobPrototype field.
            // For example, a new ID from a box would have no job index.
            if (jobIndex < 0)
            {
                jobIndex = _jobPrototypeIds.IndexOf(_defaultJob);
            }

            JobPresetOptionButton.SelectId(jobIndex);

            _lastFullName = state.TargetIdFullName;
            _lastJobTitle = state.TargetIdJobTitle;
            _lastJobProto = state.TargetIdJobPrototype;
        }

        private void SubmitData()
        {
            // Don't send this if it isn't dirty.
            var jobProtoDirty = _lastJobProto != null &&
                                _jobPrototypeIds[JobPresetOptionButton.SelectedId] != _lastJobProto;

            _owner.SubmitData(
                FullNameLineEdit.Text,
                JobTitleLineEdit.Text,
                // Iterate over the buttons dictionary, filter by `Pressed`, only get key from the key/value pair
                _accessButtons.ButtonsList.Where(x => x.Value.Pressed).Select(x => x.Key).ToList(),
                jobProtoDirty ? _jobPrototypeIds[JobPresetOptionButton.SelectedId] : string.Empty);
        }
    }
}
