using System.Linq;
using System.Numerics;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mini.AntagTokens;
using Content.Shared._Mini.ReadyManifest;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Mini.ReadyManifest;

[GenerateTypedNameReferences]
public sealed partial class ReadyManifestUi : DefaultWindow
{
    private readonly IPrototypeManager _prototypeManager;
    private readonly Dictionary<string, BoxContainer> _jobCategories;
    private readonly SpriteSystem _spriteSystem;
    private readonly Texture _coinTexture;

    public ReadyManifestUi()
    {
        RobustXamlLoader.Load(this);
        _jobCategories = new Dictionary<string, BoxContainer>();
        _prototypeManager = IoCManager.Resolve<IPrototypeManager>();
        _spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

        var cache = IoCManager.Resolve<IResourceCache>();
        _coinTexture = cache.TryGetResource<TextureResource>(
                new ResPath(AntagTokenCatalog.CurrencyIconPath), out var antagCoin)
            ? antagCoin.Texture
            : cache.GetTexture("/Textures/_Mini/Interface/Coin.png");
    }

    public void RebuildUI(
        Dictionary<ProtoId<JobPrototype>, List<string>> jobCharacters,
        List<ReadyManifestAntagEntry> antagQueue)
    {
        RebuildAntagQueue(antagQueue);
        RebuildJobs(jobCharacters);
    }

    private void RebuildAntagQueue(List<ReadyManifestAntagEntry> antagQueue)
    {
        AntagQueueSection.DisposeAllChildren();
        AntagQueueSection.Visible = antagQueue.Count > 0;
        if (antagQueue.Count == 0)
            return;

        var stripe = new StripeBack();
        stripe.AddChild(new Label
        {
            StyleClasses = { "LabelBig" },
            Text = Loc.GetString("ready-manifest-antag-queue-title"),
            Align = Label.AlignMode.Center,
        });
        AntagQueueSection.AddChild(stripe);

        AntagQueueSection.AddChild(new Label
        {
            Text = Loc.GetString("ready-manifest-antag-queue-hint"),
            FontColorOverride = Color.Gray,
            Margin = new Thickness(4, 2, 4, 6),
        });

        foreach (var entry in antagQueue)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 4,
                Margin = new Thickness(8, 2, 8, 4),
            };

            row.AddChild(new Label
            {
                Text = Loc.GetString(
                    "ready-manifest-antag-queue-entry",
                    ("position", entry.QueuePosition),
                    ("name", entry.CharacterName),
                    ("role", entry.RoleName)),
                VerticalAlignment = VAlignment.Center,
            });

            row.AddChild(new Label
            {
                Text = entry.Cost.ToString(),
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(6, 0, 0, 0),
            });

            row.AddChild(new TextureRect
            {
                Texture = _coinTexture,
                MinSize = new Vector2(16, 16),
                MaxSize = new Vector2(16, 16),
                TextureScale = new Vector2(0.3f, 0.3f),
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(4, 0, 0, 0),
            });

            AntagQueueSection.AddChild(row);
        }
    }

    private void RebuildJobs(Dictionary<ProtoId<JobPrototype>, List<string>> jobCharacters)
    {
        ReadyManifestListing.DisposeAllChildren();
        _jobCategories.Clear();

        var departments = new List<DepartmentPrototype>();
        foreach (var department in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
        {
            if (department.EditorHidden)
                continue;

            departments.Add(department);
        }

        departments.Sort(DepartmentUIComparer.Instance);

        var anyJobs = false;

        foreach (var department in departments)
        {
            var departmentName = Loc.GetString($"department-{department.ID}");
            BoxContainer? category = null;

            var jobs = department.Roles
                .Select(jobId => _prototypeManager.Index(jobId))
                .ToArray();

            Array.Sort(jobs, JobUIComparer.Instance);

            foreach (var job in jobs)
            {
                if (!jobCharacters.TryGetValue(job.ID, out var characters) || characters.Count == 0)
                    continue;

                anyJobs = true;

                if (category == null)
                {
                    category = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Vertical,
                        HorizontalExpand = true,
                        Name = department.ID,
                        ToolTip = Loc.GetString(
                            "humanoid-profile-editor-jobs-amount-in-department-tooltip",
                            ("departmentName", departmentName)),
                    };

                    var stripe = new StripeBack();
                    stripe.AddChild(new Label
                    {
                        StyleClasses = { "LabelBig" },
                        Text = Loc.GetString($"department-{department.ID}"),
                        Align = Label.AlignMode.Center,
                    });
                    category.AddChild(stripe);

                    _jobCategories[department.ID] = category;
                    ReadyManifestListing.AddChild(category);
                }

                var gridContainer = new GridContainer
                {
                    HorizontalExpand = true,
                    Columns = 2,
                };

                var jobContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                };

                var title = new RichTextLabel { HorizontalExpand = true };
                title.SetMessage(job.LocalizedName + ":");

                var icon = new TextureRect
                {
                    TextureScale = new Vector2(2, 2),
                    VerticalAlignment = VAlignment.Center,
                    Margin = new Thickness(0, 0, 4, 0),
                };

                if (_prototypeManager.TryIndex(job.Icon, out var jobIcon))
                    icon.Texture = _spriteSystem.Frame0(jobIcon.Icon);

                var readyCount = new RichTextLabel { HorizontalExpand = true };
                readyCount.SetMessage(characters.Count.ToString());

                jobContainer.AddChild(icon);
                jobContainer.AddChild(title);
                gridContainer.AddChild(jobContainer);
                gridContainer.AddChild(readyCount);
                category.AddChild(gridContainer);

                var namesContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    Margin = new Thickness(20, 0, 0, 5),
                };

                foreach (var characterName in characters.OrderBy(n => n))
                {
                    namesContainer.AddChild(new Label
                    {
                        Text = "• " + characterName,
                        FontColorOverride = Color.LightGray,
                    });
                }

                category.AddChild(namesContainer);
            }
        }

        if (!anyJobs)
        {
            ReadyManifestListing.AddChild(new Label
            {
                Text = Loc.GetString("ready-manifest-empty"),
                Align = Label.AlignMode.Center,
                FontColorOverride = Color.Gray,
                Margin = new Thickness(8),
            });
        }
    }
}
