#!/usr/bin/env python3
"""Generate the syndicate (black/red) smartfridge RSI for Typan."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

from PIL import Image

from generate_typan_vending_rsis import recolor_rgba

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "Resources" / "Textures" / "Structures" / "Machines" / "smartfridge.rsi"
DST = ROOT / "Resources" / "Textures" / "_Mini" / "Structures" / "Machines" / "smartfridge.rsi"

# The door layer is drawn unshaded in the prototype (lit display glass).
UNSHADED_STATES = {"smartfridge_door"}


def main() -> int:
    if DST.exists():
        shutil.rmtree(DST)
    DST.mkdir(parents=True, exist_ok=True)

    meta = json.loads((SRC / "meta.json").read_text(encoding="utf-8"))
    meta["copyright"] = (
        meta.get("copyright", "")
        + " Recolored to Typan black/red palette for Mini Station "
        "(auto-generated by Tools/generate_typan_smartfridge_rsi.py)."
    ).strip()
    (DST / "meta.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")

    for png in sorted(SRC.glob("*.png")):
        is_unshaded = png.stem in UNSHADED_STATES or "unshaded" in png.name.lower()
        out = recolor_rgba(Image.open(png), is_unshaded=is_unshaded, palette="default")
        out.save(DST / png.name, format="PNG", optimize=False, compress_level=6)
        print(f"  {png.name} ({'unshaded' if is_unshaded else 'shaded'})")

    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
