// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.GameTicking.Managers;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Store.Ui;

// goob edit - fuck newstore
// do not touch unless you want to shoot yourself in the leg
[GenerateTypedNameReferences]
public sealed partial class StoreListingControl : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    private readonly ClientGameTicker _ticker;

    private readonly ListingData _data;

    private readonly bool _hasBalance;
    private readonly string _price;
    private readonly Color _accent;
    private readonly StyleBoxFlat _cardStyle;
    private readonly StyleBoxFlat _railStyle;

    private static readonly Color CardBg = Color.FromHex("#151A24");
    private static readonly Color CardBgHover = Color.FromHex("#1C2433");
    private static readonly Color CardBgDisabled = Color.FromHex("#10141C");

    public StoreListingControl(
        ListingData data,
        string price,
        bool hasBalance,
        Texture? texture = null,
        Color? accent = null,
        Texture? currencyTexture = null,
        EntProtoId? productPrototype = null)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _ticker = _entity.System<ClientGameTicker>();

        _data = data;
        _hasBalance = hasBalance;
        _price = price;
        _accent = accent ?? Color.FromHex("#C23B3B");

        _cardStyle = (StyleBoxFlat) PanelOverride!;
        _railStyle = (StyleBoxFlat) AccentRail.PanelOverride!;
        _railStyle.BackgroundColor = _accent;
        _cardStyle.BorderColor = Color.FromHex("#2A3344").WithAlpha(0.9f);
        _cardStyle.BackgroundColor = hasBalance ? CardBg : CardBgDisabled;

        StoreItemName.Text = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype);
        StoreItemName.FontColorOverride = Color.FromHex("#F2F4F8");
        StoreItemDescription.SetMessage(ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(_data, _prototype));

        // Prefer live entity sprite (layered mags show ammo). Custom listing icons win when no product entity view.
        if (productPrototype != null)
        {
            StoreItemEntity.SetPrototype(productPrototype.Value);
            StoreItemEntity.Visible = true;
            StoreItemTexture.Visible = false;
        }
        else if (texture != null)
        {
            StoreItemTexture.Texture = texture;
            StoreItemTexture.Visible = true;
            StoreItemEntity.Visible = false;
        }

        if (currencyTexture != null)
        {
            CurrencyIcon.Texture = currencyTexture;
            CurrencyIcon.Visible = true;
        }

        UpdateBuyButtonText();
        StoreItemBuyButton.Disabled = !CanBuy();
        if (CanBuy())
            StoreItemBuyButton.ModulateSelfOverride = _accent;

        OnMouseEntered += _ =>
        {
            if (CanBuy())
                _cardStyle.BackgroundColor = CardBgHover;
        };
        OnMouseExited += _ =>
        {
            _cardStyle.BackgroundColor = CanBuy() ? CardBg : CardBgDisabled;
        };
    }

    private bool CanBuy()
    {
        if (!_hasBalance)
            return false;

        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        if (_data.RestockTime > stationTime)
            return false;

        return true;
    }

    private void UpdateBuyButtonText()
    {
        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        if (_data.RestockTime > stationTime)
        {
            var timeLeftToBuy = stationTime - _data.RestockTime;
            BuyPriceLabel.Text = timeLeftToBuy.Duration().ToString(@"mm\:ss");
            CurrencyIcon.Visible = false;
        }
        else
        {
            BuyPriceLabel.Text = _price;
            CurrencyIcon.Visible = CurrencyIcon.Texture != null;
        }
    }

    private void UpdateName()
    {
        var name = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype);

        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        if (_data.RestockTime > stationTime)
        {
            name += Loc.GetString("store-ui-button-out-of-stock");
        }

        StoreItemName.Text = name;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // Wrap description to the text column only (buy button lives under the icon).
        var wrapWidth = TextColumn.Width;
        if (wrapWidth > 1f)
            StoreItemDescription.MaxWidth = wrapWidth;

        UpdateBuyButtonText();
        UpdateName();
        StoreItemBuyButton.Disabled = !CanBuy();
        if (CanBuy())
            StoreItemBuyButton.ModulateSelfOverride = _accent;
        else
            StoreItemBuyButton.ModulateSelfOverride = null;
    }
}
