// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.Actions;
using Content.Client.Message;
using Content.Goobstation.Maths.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.Store.Ui;

// goob edit - fuck newstore
// do not touch unless you want to shoot yourself in the leg
[GenerateTypedNameReferences]
public sealed partial class StoreMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private StoreWithdrawWindow? _withdrawWindow;

    public event EventHandler<string>? SearchTextUpdated;
    public event Action<BaseButton.ButtonEventArgs, ListingData>? OnListingButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, string>? OnCategoryButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, string, int>? OnWithdrawAttempt;
    public event Action<BaseButton.ButtonEventArgs>? OnRefundAttempt;

    public Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> Balance = new();
    public string CurrentCategory = string.Empty;

    private List<ListingData> _cachedListings = new();

    private static readonly Color DefaultAccent = Color.FromHex("#C23B3B");
    private static readonly Color CategoryBg = Color.FromHex("#141A24");
    private static readonly Color CategoryBgSelected = Color.FromHex("#2A3A55");

    public StoreMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WithdrawButton.OnButtonDown += OnWithdrawButtonDown;
        RefundButton.OnButtonDown += OnRefundButtonDown;
        SearchBar.OnTextChanged += _ => SearchTextUpdated?.Invoke(this, SearchBar.Text);
    }

    public void UpdateBalance(Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> balance)
    {
        Balance = balance;

        var currency = balance.ToDictionary(type =>
            (type.Key, type.Value), type => _prototypeManager.Index(type.Key));

        var balanceStr = string.Empty;
        foreach (var ((_, amount), proto) in currency)
        {
            balanceStr += Loc.GetString("store-ui-balance-display", ("amount", amount),
                ("currency", Loc.GetString(proto.DisplayName, ("amount", 1)))) + "\n";
        }

        BalanceInfo.SetMarkup($"[color=#F2F4F8][bold]{balanceStr.TrimEnd()}[/bold][/color]");

        var disabled = true;
        foreach (var type in currency)
        {
            if (type.Value.CanWithdraw && type.Value.Cash != null && type.Key.Item2 > 0)
            {
                disabled = false;
                break;
            }
        }

        WithdrawButton.Disabled = disabled;
    }

    public void UpdateListing(List<ListingData> listings)
    {
        _cachedListings = listings;

        UpdateListing();
    }

    public void UpdateListing()
    {
        var sorted = _cachedListings.OrderBy(l => l.Priority).ThenBy(l => l.Cost.Values.Sum()).ThenBy(l => l.Name == null ? string.Empty : Loc.GetString(l.Name)); // Goob edit

        // should probably chunk these out instead. to-do if this clogs the internet tubes.
        // maybe read clients prototypes instead?
        ClearListings();
        foreach (var item in sorted)
        {
            AddListingGui(item);
        }
    }

    public void SetFooterVisibility(bool visible)
    {
        TraitorFooter.Visible = visible;
    }

    private void OnWithdrawButtonDown(BaseButton.ButtonEventArgs args)
    {
        // check if window is already open
        if (_withdrawWindow != null && _withdrawWindow.IsOpen)
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        // open a new one
        _withdrawWindow = new StoreWithdrawWindow();
        _withdrawWindow.OpenCentered();

        _withdrawWindow.CreateCurrencyButtons(Balance);
        _withdrawWindow.OnWithdrawAttempt += OnWithdrawAttempt;
    }

    private void OnRefundButtonDown(BaseButton.ButtonEventArgs args)
    {
        OnRefundAttempt?.Invoke(args);
    }

    private void AddListingGui(ListingData listing)
    {
        if (!listing.Categories.Contains(CurrentCategory))
            return;

        var listingPrice = listing.Cost;
        var hasBalance = HasListingPrice(Balance, listingPrice);

        var spriteSys = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();

        Texture? texture = null;
        EntProtoId? productProto = null;

        // Show real product sprites for magazines/speedloaders so MagazineVisuals ammo layers appear.
        // Custom listing icons are used for boxes / special catalog art.
        if (listing.ProductEntity != null && PreferEntityProductSprite(listing.ProductEntity.Value))
        {
            productProto = listing.ProductEntity;
        }
        else if (listing.Icon != null)
        {
            texture = spriteSys.Frame0(listing.Icon);
        }
        else if (listing.ProductEntity != null)
        {
            productProto = listing.ProductEntity;
        }
        else if (listing.ProductAction != null)
        {
            var actionId = _entityManager.Spawn(listing.ProductAction);
            if (_entityManager.System<ActionsSystem>().GetAction(actionId)?.Comp?.Icon is {} icon)
                texture = spriteSys.Frame0(icon);
        }

        var accent = GetCategoryAccent(CurrentCategory);
        var (priceText, currencyTex) = GetListingPriceDisplay(listing, spriteSys);
        var newListing = new StoreListingControl(listing, priceText, hasBalance, texture, accent, currencyTex, productProto);

        if (listing.DiscountValue > 0) // WD EDIT
            newListing.StoreItemBuyButton.AddStyleClass("ButtonColorRed");

        newListing.StoreItemBuyButton.OnButtonDown += args
            => OnListingButtonPressed?.Invoke(args, listing);

        StoreListingsContainer.AddChild(newListing);
    }

    private static bool PreferEntityProductSprite(EntProtoId product)
    {
        var id = product.Id;
        // Layered BallisticAmmoProvider mags — Icon/base alone looks empty in the store.
        return id.StartsWith("Magazine", StringComparison.Ordinal)
               || id.StartsWith("SpeedLoader", StringComparison.Ordinal);
    }

    public bool HasListingPrice(Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> currency, Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> price)
    {
        foreach (var type in price)
        {
            if (!currency.ContainsKey(type.Key))
                return false;

            if (currency[type.Key] < type.Value)
                return false;
        }
        return true;
    }

    private (string Text, Texture? Icon) GetListingPriceDisplay(ListingData listing, SpriteSystem spriteSys)
    {
        if (listing.Cost.Count < 1)
            return (Loc.GetString("store-currency-free"), null);

        // Prefer a single currency amount + icon (e.g. telecrystal sprite next to "2").
        if (listing.Cost.Count == 1)
        {
            var (type, amount) = listing.Cost.First();
            var currency = _prototypeManager.Index(type);
            Texture? icon = null;

            if (currency.Cash is { } cash && cash.Count > 0)
            {
                var cashProto = cash.Values.First();
                icon = spriteSys.GetPrototypeIcon(cashProto.Id).Default;
            }

            if (icon != null)
                return (amount.ToString(), icon);

            return (Loc.GetString(
                "store-ui-price-display",
                ("amount", amount),
                ("currency", Loc.GetString(currency.DisplayName, ("amount", amount)))
            ), null);
        }

        return (GetListingPriceString(listing), null);
    }

    private string GetListingPriceString(ListingData listing)
    {
        var text = string.Empty;

        if (listing.Cost.Count < 1)
            text = Loc.GetString("store-currency-free");
        else
        {
            foreach (var (type, amount) in listing.Cost)
            {
                var currency = _prototypeManager.Index(type);

                text += Loc.GetString(
                    "store-ui-price-display",
                    ("amount", amount),
                    ("currency", Loc.GetString(currency.DisplayName, ("amount", amount)))
                );
            }
        }

        return text.TrimEnd();
    }

    private void ClearListings()
    {
        StoreListingsContainer.Children.Clear();
    }

    public void PopulateStoreCategoryButtons(HashSet<ListingData> listings)
    {
        var allCategories = new List<StoreCategoryPrototype>();
        foreach (var listing in listings)
        {
            foreach (var cat in listing.Categories)
            {
                var proto = _prototypeManager.Index(cat);
                if (!allCategories.Contains(proto))
                    allCategories.Add(proto);
            }
        }

        allCategories = allCategories.OrderBy(c => c.Priority).ToList();

        // This will reset the Current Category selection if nothing matches the search.
        if (allCategories.All(category => category.ID != CurrentCategory))
            CurrentCategory = string.Empty;

        if (CurrentCategory == string.Empty && allCategories.Count > 0)
            CurrentCategory = allCategories.First().ID;

        CategoryListContainer.Children.Clear();
        if (allCategories.Count < 1)
            return;

        var group = new ButtonGroup();
        foreach (var proto in allCategories)
        {
            var accent = proto.AccentColor ?? (proto.Evil ? Color.FromHex("#D43B3B") : DefaultAccent);
            var selected = proto.ID == CurrentCategory;

            var rail = new PanelContainer
            {
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 3),
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = selected ? CategoryBgSelected : CategoryBg,
                    BorderColor = accent,
                    BorderThickness = new Thickness(3, 0, 0, 0),
                    ContentMarginLeftOverride = 2,
                    ContentMarginRightOverride = 2,
                    ContentMarginTopOverride = 0,
                    ContentMarginBottomOverride = 0,
                },
            };

            var catButton = new StoreCategoryButton
            {
                Text = Loc.GetString(proto.Name),
                Id = proto.ID,
                Pressed = selected,
                Group = group,
                ToggleMode = true,
                HorizontalExpand = true,
                MinHeight = 32,
            };

            // Selection is shown via Pressed + rail background only — don't tint with accent (looks "stuck" red).
            if (proto.Evil && !selected)
                catButton.AddStyleClass("ButtonColorRed");

            catButton.OnPressed += args => OnCategoryButtonPressed?.Invoke(args, catButton.Id!);
            rail.AddChild(catButton);
            CategoryListContainer.AddChild(rail);
        }
    }

    private Color GetCategoryAccent(string categoryId)
    {
        if (_prototypeManager.TryIndex<StoreCategoryPrototype>(categoryId, out var proto) && proto.AccentColor != null)
            return proto.AccentColor.Value;

        return DefaultAccent;
    }

    public override void Close()
    {
        base.Close();
        _withdrawWindow?.Close();
    }

    public void UpdateRefund(bool allowRefund)
    {
        RefundButton.Visible = allowRefund;
    }

    private sealed class StoreCategoryButton : Button
    {
        public string? Id;
    }
}
