using Content.Client.CrewManifest;
using Content.Client.GameTicking.Managers;
using Content.Client.Lobby;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.UserInterface.Controls;
using Content.Client._Mini.TypanWar;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Console;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Mini.Latejoin;

[GenerateTypedNameReferences]
public sealed partial class NFLateJoinGui : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IConsoleHost _consoleHost = default!;
    [Dependency] private readonly JobRequirementsManager _playManager = default!;
    [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;

    private ClientGameTicker _gameTicker;
    private TypanWarUiSystem _warUi;

    private NetEntity _lastSelection;

    private readonly Dictionary<string, BoxContainer> _jobCategories;
    private readonly Dictionary<string, NewFrontierLateJoinJobButton> _buttons = new();

    public NFLateJoinGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _gameTicker = EntitySystem.Get<ClientGameTicker>();
        _warUi = EntitySystem.Get<TypanWarUiSystem>();
        _gameTicker.LobbyJobsAvailableUpdated += UpdateUi;
        _warUi.BalanceUpdated += OnBalanceUpdated;

        _jobCategories = new Dictionary<string, BoxContainer>();
        StationSelection.StationsItemList.OnItemSelected += args =>
        {
            UpdateUi(_gameTicker.JobsAvailable);
        };
        CrewManifestButton.OnPressed += _ =>
        {
            EntitySystem.Get<CrewManifestSystem>().RequestCrewManifest(_lastSelection);
        };

        _lastSelection = _gameTicker.JobsAvailable.Keys.FirstOrNull() ?? NetEntity.Invalid;

        _warUi.RequestBalanceStatus();
        UpdateUi(_gameTicker.JobsAvailable);
        UpdateBalanceNotice();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _gameTicker.LobbyJobsAvailableUpdated -= UpdateUi;
        _warUi.BalanceUpdated -= OnBalanceUpdated;
    }

    private void OnBalanceUpdated()
    {
        UpdateBalanceNotice();
        ApplyBalanceToButtons();
    }

    public void UpdateUi(IReadOnlyDictionary<NetEntity, Dictionary<ProtoId<JobPrototype>, int?>> obj)
    {
        if (StationSelection.Selected is null)
        {
            CrewManifestButton.Visible = false;
            return;
        }

        CrewManifestButton.Visible = true;

        var station = StationSelection.Selected.Value;
        if (!obj.TryGetValue(station, out var jobs))
            return;

        if (station != _lastSelection)
        {
            foreach (var (_, button) in _buttons)
            {
                JobList.RemoveChild(button);
            }
            _buttons.Clear();
            foreach (var (_, box) in _jobCategories)
            {
                JobList.RemoveChild(box);
            }
            _jobCategories.Clear();
        }

        _lastSelection = station;

        var departments = new List<DepartmentPrototype>();
        foreach (var department in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
        {
            if (department.EditorHidden)
                continue;

            departments.Add(department);
        }

        departments.Sort(DepartmentUIComparer.Instance);

        foreach (var department in departments)
        {
            var departmentName = Loc.GetString($"department-{department.ID}");

            var hasRole = false;
            foreach (var (jobId, _) in jobs)
            {
                if (department.Roles.Contains(jobId))
                {
                    hasRole = true;
                    break;
                }
            }

            if (!hasRole)
            {
                continue;
            }

            if (!_jobCategories.TryGetValue(department.ID, out var category))
            {
                category = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Name = department.ID,
                    ToolTip = Loc.GetString("humanoid-profile-editor-jobs-amount-in-department-tooltip",
                        ("departmentName", departmentName))
                };

                var departamentLabel = new Label
                {
                    Text = Loc.GetString("humanoid-profile-editor-department-jobs-label",
                        ("departmentName", departmentName)),
                    Margin = new Thickness(5f, 0, 0, 0)
                };

                category.AddChild(new StripeBack()
                {
                    Visible = true,
                    HorizontalExpand = true,
                    HasMargins = true,
                    MouseFilter = MouseFilterMode.Stop,
                    Children =
                    {
                        departamentLabel
                    }
                });

                _jobCategories[department.ID] = category;
                JobList.AddChild(category);
            }

            foreach (var (jobId, _) in jobs)
            {
                if (!department.Roles.Contains(jobId))
                    continue;

                if (_buttons.ContainsKey(jobId))
                    continue;

                var job = _prototypeManager.Index(jobId);

                var newButton = new NewFrontierLateJoinJobButton(station, jobId, _gameTicker, _prototypeManager);
                newButton.OnPressed += _ =>
                {
                    Logger.InfoS("latejoin", $"Late joining as ID: {jobId}");
                    _consoleHost.ExecuteCommand($"joingame {CommandParsing.Escape(jobId)} {station}");
                    Close();
                };

                RefreshButtonState(newButton, jobId);

                JobList.AddChild(newButton);

                _buttons.Add(jobId, newButton);
            }
        }

        ApplyBalanceToButtons();
        UpdateBalanceNotice();
    }

    private void UpdateBalanceNotice()
    {
        if (!_warUi.BalanceActive)
        {
            BalanceNotice.Visible = false;
            return;
        }

        string? text = null;
        if (!_warUi.AllowNanotrasen && _warUi.AllowTypan)
            text = Loc.GetString("typan-war-balance-latejoin-nt-full");
        else if (!_warUi.AllowTypan && _warUi.AllowNanotrasen)
            text = Loc.GetString("typan-war-balance-latejoin-typan-full");
        else if (!_warUi.AllowNanotrasen && !_warUi.AllowTypan)
            text = Loc.GetString("typan-war-balance-latejoin-both-full");

        if (text == null)
        {
            BalanceNotice.Visible = false;
            return;
        }

        BalanceNotice.Text = text;
        BalanceNotice.Visible = true;
    }

    private void ApplyBalanceToButtons()
    {
        foreach (var (jobId, button) in _buttons)
        {
            RefreshButtonState(button, jobId);
        }
    }

    private void RefreshButtonState(NewFrontierLateJoinJobButton button, ProtoId<JobPrototype> jobId)
    {
        var job = _prototypeManager.Index(jobId);

        if (!_playManager.IsAllowed(job, (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, out var denyReason))
        {
            button.Disabled = true;
            button.ToolTip = denyReason.ToString();
            return;
        }

        if (_warUi.BalanceActive)
        {
            var isTypan = IsTypanJob(jobId);
            var blocked = isTypan ? !_warUi.AllowTypan : !_warUi.AllowNanotrasen;
            if (blocked)
            {
                button.Disabled = true;
                button.ToolTip = Loc.GetString("typan-war-balance-job-denied");
                return;
            }
        }

        if (IsJobSlotFull(jobId))
        {
            button.Disabled = true;
            button.ToolTip = Loc.GetString("late-join-gui-job-slot-full");
            return;
        }

        button.Disabled = false;
        button.ToolTip = null;
    }

    private bool IsJobSlotFull(ProtoId<JobPrototype> jobId)
    {
        if (!_gameTicker.JobsAvailable.TryGetValue(_lastSelection, out var jobs))
            return true;

        if (!jobs.TryGetValue(jobId, out var count))
            return true;

        return count == 0;
    }

    private bool IsTypanJob(ProtoId<JobPrototype> jobId)
    {
        foreach (var department in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
        {
            if (department.ID is not ("Typan" or "Typan2"))
                continue;

            if (department.Roles.Contains(jobId))
                return true;
        }

        return false;
    }
}
