# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Mindcontrolled
  name: antag-name-mindcontrolled
  antagonist: true
  setPreference: false
  objective: antag-objective-mindcontrolled