// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._Mini.Administration.GameModes;
using Content.Shared._Mini.Administration.GameModes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.GameModes;

[GenerateTypedNameReferences]
public sealed partial class GameModesWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    private GameModesAdminSystem? _system;
    private string? _selectedPresetId;
    private bool _suppressVoteToggle;

    public GameModesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _system = _entMan.System<GameModesAdminSystem>();
        _system.OnStateUpdated += Populate;
        _system.OnActionResult += OnActionResult;

        RefreshButton.OnPressed += _ => _system.RequestState();
        StartVoteButton.OnPressed += _ => _system.StartPresetVote();
        SetPresetButton.OnPressed += _ =>
        {
            if (_selectedPresetId != null)
                _system.SetPreset(_selectedPresetId);
        };
        ForcePresetButton.OnPressed += _ =>
        {
            if (_selectedPresetId != null)
                _system.ForcePreset(_selectedPresetId);
        };
        PresetsList.OnItemSelected += OnPresetSelected;
        VoteEnabledCheck.OnToggled += args =>
        {
            if (_suppressVoteToggle)
                return;
            _system.SetVoteEnabled(args.Pressed);
        };

        _system.RequestState();
    }

    private void OnPresetSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (args.ItemIndex < 0)
            return;

        if (PresetsList[args.ItemIndex].Metadata is string id)
            ShowSelected(id);
    }

    private void Populate()
    {
        var state = _system?.LastState;
        if (state == null)
            return;

        _suppressVoteToggle = true;
        VoteEnabledCheck.Pressed = state.VotePresetEnabled;
        _suppressVoteToggle = false;

        CurrentPresetLabel.Text = state.CurrentPresetName != null
            ? Loc.GetString("game-modes-admin-current", ("preset", state.CurrentPresetName))
            : Loc.GetString("game-modes-admin-current-none");

        LobbyLabel.Text = state.IsLobby
            ? Loc.GetString("game-modes-admin-lobby-yes")
            : Loc.GetString("game-modes-admin-lobby-no");

        ForcePresetButton.Disabled = !state.IsLobby;

        PresetsList.Clear();
        foreach (var preset in state.Presets)
        {
            var mark = preset.Id == state.CurrentPresetId ? "★ " : string.Empty;
            var vote = preset.ShowInVote
                ? string.Empty
                : Loc.GetString("game-modes-admin-hidden-suffix");
            PresetsList.AddItem($"{mark}{preset.Name}{vote}", metadata: preset.Id);
        }

        if (_selectedPresetId != null)
            ShowSelected(_selectedPresetId);
    }

    private void ShowSelected(string presetId)
    {
        if (_system?.LastState == null)
            return;

        var info = _system.LastState.Presets.Find(p => p.Id == presetId);
        if (info == null)
            return;

        _selectedPresetId = presetId;
        SelectedNameLabel.Text = $"{info.Name} ({info.Id})";
        var players = info.MinPlayers != null || info.MaxPlayers != null
            ? Loc.GetString("game-modes-admin-players",
                ("min", info.MinPlayers?.ToString() ?? "-"),
                ("max", info.MaxPlayers?.ToString() ?? "-"))
            : Loc.GetString("game-modes-admin-players-any");
        var vote = info.ShowInVote
            ? Loc.GetString("game-modes-admin-in-vote")
            : Loc.GetString("game-modes-admin-not-in-vote");
        SelectedMetaLabel.Text = $"{vote} · {players}";
        SelectedDescLabel.SetMessage(info.Description);
    }

    private void OnActionResult(GameModesAdminActionResult result)
    {
        StatusLabel.Text = result.Message;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && _system != null)
        {
            _system.OnStateUpdated -= Populate;
            _system.OnActionResult -= OnActionResult;
        }

        base.Dispose(disposing);
    }
}
